# abm_crm serves its own build of the CRM frontend at /crm (www/crm.html is generated by
# `yarn build`). Frappe only loads the context module that sits next to the template, so
# re-export crm's context to keep boot data, permission checks and redirects working.
from crm.www.crm import get_boot, get_context, get_context_for_dev, no_cache  # noqa: F401
